In [13]:
import pandas as pd
import numpy as np
import seaborn as sns

1- What is the output of the following expression ? 

len(list(range(10)[-1::-1]))

In [7]:
len(list(range(10)[-1::-1])), list(range(10)[-1::-1])

(10, [9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2- What is the output of the following code ? 

array = np.array(range(74))

np.argmax(np.sort(array)-np.sum(array))

In [14]:
array = np.array(range(74))
np.argmax(np.sort(array) - np.sum(array))

np.int64(73)

1. What is the sum of the first 100 positive integers?

Use the formula n(n+1)/2. Define n=100 and 
then use python to compute the sum, using the formula. What is the value of the sum?

In [15]:
n = 100
sum = n * (n+1) / 2

print(sum)

5050.0

In [18]:
x = np.arange(1, 1001)
np.sum(x)

np.int64(500500)

2- Compute the sum of $1/k^2$ for $k = 1,2,...,100$ and comapre it to $\pi^2 / 6$

In [23]:
k = 100
k_sum = np.sum(1 / np.arange(1,101) ** 2)

pi_square_over_six = np.pi**2 / 6

print(k_sum, pi_square_over_six, np.abs(k_sum - pi_square_over_six))

1.6349839001848931 1.6449340668482264 0.00995016666333326

# Basic Data

In [27]:
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Columns

In [30]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

## Columns Types

In [31]:
a = tips['tip']
a.dtype

dtype('float64')

In [32]:
b = tips['day']
b.dtype

CategoricalDtype(categories=['Thur', 'Fri', 'Sat', 'Sun'], ordered=False, categories_dtype=object)

In [43]:
list(tips['time'].dtype.categories)

['Lunch', 'Dinner']

## np.unique() 
### with parameter return_counts

In [45]:
x = np.array(['DC', 'Alabama', 'Florida', 'Florida', 'DC', 'DC'])
unique_values = np.unique(x, return_counts=True)

print('Values: ', unique_values[0])
print('Counts: ', unique_values[1])

Values:  ['Alabama' 'DC' 'Florida']
Counts:  [1 3 2]

now apply this idea to day column of the tips data.

convert the day column to a numpy array using 'values' attribute and compute how many bills were recorded for each day.

In [50]:
x = tips['day'].values
unique_days, days_count = np.unique(x, return_counts=True)

print('Days: ', unique_days)
print('Counts: ', days_count)

Days:  ['Fri' 'Sat' 'Sun' 'Thur']
Counts:  [19 87 76 62]

# Create a new column

In [55]:
tips_percentage = tips['tip'].values / tips['total_bill'].values
tips_percentage.argmax()

np.int64(172)

# Working with Arrays

In [56]:
temp = np.array([35, 88, 42, 84, 81, 30])

Acces to first three

In [58]:
temp[:3]

array([35, 88, 42])

Create a dict cities_temp that will have for the next cities: Beijing, Lagos, Paris, and San Juan,
with corresponding temperatures: 35, 88, 42and 84 degrees Fahrenheit.

In [59]:
cities_temp = {
    'Beijing': 35,
    'Lagos': 88,
    'Paris': 42,
    'San Juan': 84
}

In [ ]:
cities_temp['Paris']

42

Use range to create a list of number $12, 13, ... , 73$

In [75]:
a = list(range(12,74))
a[0], a[-1]

(12, 73)

Create a vector containing all the positive odd numbers smaller than 100

In [79]:
x = 2 * np.arange(0,50) + 1
y = np.arange(1, 100, 2)

x, y

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]))

Create a vector of numbers that starts at $6$, does not pass $55$, and adds numbers in increments of $4/7$

In [82]:
z = np.arange(6, 55, 4/7)
len(z)

86

# Homework

In [83]:
bills = tips['total_bill'].values

2. Sort the total_bill column of tips dataset and report smallest value.

In [85]:
np.sort(bills)[0]

np.float64(3.07)

3. Find index of smallest total_bill in the bills array

In [87]:
x = bills.argmin()
y = np.argmin(bills)
x,y

(np.int64(67), np.int64(67))

## Vector Arithmetics

Use the temp vector to create a different vector temp_C that converts the temperature from Fahrenheit to
Celsius. The conversion is $𝐶 = 5/9 × (𝐹 − 32)$.

In [89]:
temp = np.array([35, 88, 42, 84, 81, 30])

temp_C = 5/9 * (temp - 32)
temp_C

array([ 1.66666667, 31.11111111,  5.55555556, 28.88888889, 27.22222222,
       -1.11111111])

# Titanic Dataset

In [91]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [96]:
titanic['age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

However, when we compute the average with the function mean, we obtain $nan$:

In [98]:
titanic['age'].values.mean()

np.float64(nan)

## isna

The *isna* function, applied to the column of the dataset, returns a logical vector that tells us which
entries are nan. Assign this logical vector to an object called ind and determine how many nans does
age have.

In [104]:
ind = titanic['age'].isna()
ind.sum()

np.int64(177)

In [114]:
ind_np = np.isnan(titanic['age'].values)

(
titanic['age'].values[~ind_np].mean(), 
titanic['age'].mean()
)

(np.float64(29.69911764705882), np.float64(29.69911764705882))