In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({"x": range(6, 0, -1), "y": [True]*3 + [False]*3})
df

   x      y
0  6   True
1  5   True
2  4   True
3  3  False
4  2  False
5  1  False

2. Find the last 10 flights arriving in LAX on Christmas Eve (24. December). Don’t worry about sorting
for now, just find the last 10 entries in the table.

                flights[(flights['MONTH'] == 12) & (flights['DAY'] == 24) & (flights['DESTINATION_AIRPORT']
                == 'LAX')].tail(10)

3. Calculate the total number of outbound flights in the summer months (June - August) by airport

        flights[flights['MONTH'].isin(range(6,9))].groupby('ORIGIN_AIRPORT').size()

-----

# Tutorial

In [11]:
users_dt = pd.read_csv('../Datasets/Exercise2_datasets/BX-Users.csv')
books_dt = pd.read_csv('../Datasets/Exercise2_datasets/BX-Books.csv')
ratings_dt = pd.read_csv('../Datasets/Exercise2_datasets/BX-Book-Ratings.csv')

1. What are the column names of the users_df DataFrame? What are the types of the columns in
users_df DataFrame. Then change the type of the Age column in users_df to numeric. Hint: `astype`.

In [22]:
col_name = users_dt.columns
print('Column Names: {}'.format(', '.join(list(col_name))))


print('Age dtype: {}'.format(users_dt['Age'].dtype))
users_dt['Age'] = users_dt['Age'].astype('Int64')
print('Age dtype: {}'.format(users_dt['Age'].dtype))

Column Names: User-ID, Location, Age
Age dtype: float64
Age dtype: Int64

In [25]:
users_dt.dtypes

User-ID      int64
Location    object
Age          Int64
dtype: object

2. Produce a summary of the numerical variables in ratings_df.

In [24]:
ratings_dt.describe()

            User-ID   Book-Rating  Year-Of-Publication
count  1.012378e+06  1.012378e+06         1.012378e+06
mean   1.404083e+05  2.829103e+00         1.967890e+03
std    8.035024e+04  3.852739e+00         2.323526e+02
min    2.000000e+00  0.000000e+00         0.000000e+00
25%    7.031800e+04  0.000000e+00         1.992000e+03
50%    1.408790e+05  0.000000e+00         1.997000e+03
75%    2.113030e+05  7.000000e+00         2.001000e+03
max    2.788540e+05  1.000000e+01         2.050000e+03

4. Return the first 5 and last 5 observations of the DataFrame ratings_df

In [27]:
ratings_dt.head(5)

,ISBN,User-ID,Book-Rating,Book-Title,Book-Author,Year-Of-Publication
0,0000913154,171118,8,The Way Things Work: An Illustrated Encycloped...,C. van Amerongen (translator),1967
1,0001010565,86123,0,Mog's Christmas,Judith Kerr,1992
2,0001010565,209516,0,Mog's Christmas,Judith Kerr,1992
3,0001046438,23902,9,Liar,Stephen Fry,0
4,0001046713,196149,0,Twopence to Cross the Mersey,Helen Forrester,1992

In [28]:
ratings_dt.tail(5)

,ISBN,User-ID,Book-Rating,Book-Title,Book-Author,Year-Of-Publication
1012373,B000234N76,264317,0,Falling Angels,Tracy Chevalier,2001
1012374,B000234NC6,100906,0,It Must've Been Something I Ate: The Return of...,Jeffrey Steingarten,2002
1012375,B00029DGGO,100088,0,"Good Wife Strikes Back, The",Elizabeth Buchan,0
1012376,B0002JV9PY,179791,0,The Blockade Runners,Jules Verne,0
1012377,B0002K6K8O,179791,0,The Underground City,Jules Verne,0

-------

Clean up column names.

 Replace the hyphens “-” with underscores “_“, this makes it easier to
reference columns. Use this line of code to change the column names of your DataFrames:

        df.columns = df.columns.str.replace('-', '_', regex=False)‘

In [31]:
for dt in [users_dt, books_dt, ratings_dt]:
    dt.columns = dt.columns.str.replace('-', '_', regex = False)

------

5. Delete the columns <u>Image_URL_S</u>, <u>Image_URL_M</u> and <u>Image_URL_L</u> in the DataFrame books_df.

In [32]:
books_dt = books_dt.drop(columns = ['Image_URL_S', 'Image_URL_M', 'Image_URL_L'])

6. Create a DataFrame book_df_2 that contains all the books published between 1900 and 2019 (inclusive) from the DataFrame books_df.

In [ ]:
book_df_2 = books_dt[books_dt['Year_Of_Publication'].isin(range(1900,2020))]

----------

# Section 02 - Data Exploration

1. How many different authors are included in the DataFrame books_df?

In [87]:
books_dt['Book_Author'].nunique()

98538

2. How many different authors are included for each year of publication between 2000 and 2010 (inclusive)
in books_dt?

In [52]:
books_dt[books_dt['Year_Of_Publication'] \
.isin(range(2000,2011))] \
.groupby('Year_Of_Publication') \
.agg({'Book_Author':'nunique'}).reset_index()

   Year_Of_Publication  Book_Author
0                 2000        12057
1                 2001        11818
2                 2002        11942
3                 2003         9913
4                 2004         4536
5                 2005           38
6                 2006            3
7                 2008            1
8                 2010            2

In [54]:
books_dt[ books_dt['Year_Of_Publication'] \
            .isin(range(2000,2011))]\
            .groupby('Year_Of_Publication')['Book_Author']\
            .nunique()

Year_Of_Publication
2000    12057
2001    11818
2002    11942
2003     9913
2004     4536
2005       38
2006        3
2008        1
2010        2
Name: Book_Author, dtype: int64

3. In how many observations is the age information missing in the DataFrame users_dt?

In [55]:
users_dt['Age'].isna().sum()

np.int64(108026)

In [56]:
users_dt[users_dt.Age.isna()].shape[0]

108026

4. What is the maximum rating value in the ratings DataFrame?

In [59]:
ratings_dt['Book_Rating'].max()

10

5. What is the most common rating value larger than 0? Hint: use mode()

In [66]:
ratings_dt[ ratings_dt['Book_Rating'] != 0]['Book_Rating'].mode()

0    8
Name: Book_Rating, dtype: int64

6. Which are the book identifiers (ISBN) with the highest ratings? Return first 10 values from teh
resulting table

In [75]:
ratings_dt[ratings_dt.Book_Rating == max(ratings_dt.Book_Rating)]['ISBN'].head(10)

28     0001360469
31     0001374869
45     0001821326
57     0001845039
66     0001857258
68     0001900277
70     0001935968
83     0001953877
88     0001981323
110    0002005050
Name: ISBN, dtype: object

7. Reorder the ratings table according to the rating value in descending order. Hint: order()

In [76]:
ratings_dt.sort_values(by = 'Book_Rating', ascending= False)

,ISBN,User_ID,Book_Rating,Book_Title,Book_Author,Year_Of_Publication
189543,0345404114,166637,10,Sleepers,Lorenzo Carcaterra,1996
735776,0684874350,273190,10,ANGELA'S ASHES,Frank McCourt,1996
735767,0684874350,263357,10,ANGELA'S ASHES,Frank McCourt,1996
735765,0684874350,263325,10,ANGELA'S ASHES,Frank McCourt,1996
78694,0140285679,167750,10,About a Boy,Nick Hornby,2002
...,...,...,...,...,...,...
413921,0440235596,144925,0,Tara Road,Maeve Binchy,2000
413922,0440235596,146113,0,Tara Road,Maeve Binchy,2000
413926,0440235596,153042,0,Tara Road,Maeve Binchy,2000
413927,0440235596,153054,0,Tara Road,Maeve Binchy,2000
1012377,B0002K6K8O,179791,0,The Underground City,Jules Verne,0

8. You are given the starwars data table which contains data of different characters appearing in the
Star Wars movies. A few rows from the data table are shown below.

In [79]:
star_wars_df = pd.read_csv('../Datasets/Exercise2_datasets/star_wars_character_dataset.csv',
                    usecols = ["name", "height", "mass", "birth_year", "sex", "homeworld", "species"])

star_wars_df = star_wars_df.rename(columns = {'birth_year': 'age'})
star_wars_df.head()

             name  height   mass    age     sex homeworld species
0  Luke Skywalker   172.0   77.0   19.0    male  Tatooine   Human
1           C-3PO   167.0   75.0  112.0    none  Tatooine   Droid
2           R2-D2    96.0   32.0   33.0    none     Naboo   Droid
3     Darth Vader   202.0  136.0   41.9    male  Tatooine   Human
4     Leia Organa   150.0   49.0   19.0  female  Alderaan   Human

a) Find the number of individuals from each species with a height over 200.

In [83]:
star_wars_df[star_wars_df['height'] > 200].groupby('species').size()

species
Gungan      2
Human       1
Kaleesh     1
Kaminoan    2
Pau'an      1
Quermian    1
Wookiee     2
dtype: int64

b) Find the mean age of each species and filter the results for species that have mean age greater than
70

In [98]:
mean_age = star_wars_df.groupby('species')['age'].mean()

mean_age[ mean_age > 70]

species
Cerean             92.0
Hutt              600.0
Wookiee           200.0
Yoda's species    896.0
Name: age, dtype: float64

c) Which are the top-10 species with the highest average body-mass-index (BMI)? BMI is given by
mass $\text{kg}/\text{height}^2$
(meters). Hint: leaving 0’s in the denominator or NANs when calculating the
mean could lead to errors! 

Also make sure height and mass are in the correct unit.

In [108]:
star_wars_df2 = star_wars_df[ ~star_wars_df['height'].isin([0, pd.NA])]

star_wars_df2['height'] = star_wars_df2['height'] / 100
star_wars_df2['BMI'] = star_wars_df2['mass'] / star_wars_df2['height']**2

star_wars_df2.groupby('species')['BMI'].mean().sort_values(ascending= False).head(10).index

Index(['Hutt', 'Vulptereen', 'Yoda's species', 'Kaleesh', 'Droid', 'Dug',
       'Trandoshan', 'Sullustan', 'Zabrak', 'Besalisk'],
      dtype='object', name='species')

-----

# Homework

## Section 03 - Manipulating data tables

1. Add a new column called High_Rating to the DataFrame ratings_df. The column has an integer
1 for all observations with a rating value higher than 7. Hint: You can create a boolean variable and
then convert it to int.

In [112]:
ratings_dt['High_Rating'] = (ratings_dt['Book_Rating'] > 7).astype('Int64')

ratings_dt.head()

,ISBN,User_ID,Book_Rating,Book_Title,Book_Author,Year_Of_Publication,High_Rating
0,0000913154,171118,8,The Way Things Work: An Illustrated Encycloped...,C. van Amerongen (translator),1967,1
1,0001010565,86123,0,Mog's Christmas,Judith Kerr,1992,0
2,0001010565,209516,0,Mog's Christmas,Judith Kerr,1992,0
3,0001046438,23902,9,Liar,Stephen Fry,0,1
4,0001046713,196149,0,Twopence to Cross the Mersey,Helen Forrester,1992,0

2. How many observations are considered to be a high ranking? What is the proportion of high ranked
observations among all observations?

In [128]:
count = ratings_dt['High_Rating'].sum()
proportion = count / (ratings_dt.size - count)
print('High Ratings: {}\nProportion: {:.2f}%'.format(count, proportion * 100))

High Ratings: 219361
Proportion: 3.19%

3. Which users did not give any rating to any book? Create a DataFrame that is a subset of users_df
excluding users who did not give any rating. Hint: There’s no need to merge users_df with ratings_df,
we are simply interested in the users that are not in ratings_df.

In [138]:
users_dt[~ users_dt['User_ID'].isin(ratings_dt['User_ID'].unique())]

        User_ID                                Location   Age
0             1                      nyc, new york, usa  <NA>
2             3         moscow, yukon territory, russia  <NA>
3             4               porto, v.n.gaia, portugal    17
4             5      farnborough, hants, united kingdom  <NA>
5             6           santa monica, california, usa    61
...         ...                                     ...   ...
269051   278102               innsbruck, tirol, austria    34
269052   278103                baltimore, maryland, usa    46
269054   278105                  marseille, n/a, france    23
269057   278108  christchurch, new zealand, new zealand    18
269058   278109              malvern, pennsylvania, usa    16

[180942 rows x 3 columns]

4. What is the most common age of users who rated at least one book?

In [141]:
users_dt[users_dt['User_ID'].isin(ratings_dt['User_ID'].unique())]['Age'].mode()

0    26
Name: Age, dtype: Int64

5. What is the average number of books rated per user?

In [149]:
ratings_dt.groupby('User_ID').size().mean()

np.float64(11.241399986675253)

6. What is the title of the first published book with the highest ranking? Hint: assume that year of
publication being zero is an error.

In [158]:
ratings_dt[(~ratings_dt['Year_Of_Publication'].isin([np.nan, 0])) & (ratings_dt['Book_Rating'] == 10)] \
.sort_values(by = 'Year_Of_Publication', ascending= True).iloc[0]['Book_Title']

'Dalan-i bihisht (Dastan-i Irani)'

7. In which year was the book with the largest number of ratings published? For simplicity we consider
that that there are no ties and only one book has the largest number of ratings.

In [169]:
name = ratings_dt.groupby('Book_Title').size().sort_values(ascending= False).index[0]
books_dt[ books_dt['Book_Title'] == name]['Year_Of_Publication']

26    2004
Name: Year_Of_Publication, dtype: int64

8. Add to the table ratings_dt the highest ranking that each book received as a new column called
Max_Book_Ranking.

In [190]:
ratings_dt['Max_Rating'] = (ratings_dt.groupby('Book_Title')['Book_Rating']).transform('max')
ratings_dt.head()

,ISBN,User_ID,Book_Rating,Book_Title,Book_Author,Year_Of_Publication,High_Rating,Max_Rating
0,0000913154,171118,8,The Way Things Work: An Illustrated Encycloped...,C. van Amerongen (translator),1967,1,8
1,0001010565,86123,0,Mog's Christmas,Judith Kerr,1992,0,0
2,0001010565,209516,0,Mog's Christmas,Judith Kerr,1992,0,0
3,0001046438,23902,9,Liar,Stephen Fry,0,1,9
4,0001046713,196149,0,Twopence to Cross the Mersey,Helen Forrester,1992,0,0

9. Subset the ratings_dt ratings table to contain only books written by the following authors:

        authors = ["Agatha Christie", "William Shakespeare", "Stephen King",
        "Ann M. Martin", "Carolyn Keene", "Francine Pascal",
        "Isaac Asimov", "Nora Roberts", "Barbara Cartland", "Charles Dickens"]

In [197]:
authors = ["Agatha Christie", "William Shakespeare", "Stephen King",
        "Ann M. Martin", "Carolyn Keene", "Francine Pascal",
        "Isaac Asimov", "Nora Roberts", "Barbara Cartland", "Charles Dickens"]

subset_rt = ratings_dt[ratings_dt['Book_Author'].isin(authors)]

10. How many ratings has each author from the previous exercise 9? What is their max and average
ranking? Hint: use function agg() from the lecture.

In [198]:
subset_rt.groupby('Book_Author').agg({
    'Book_Rating':['max', 'mean']
})

                    Book_Rating
                            max      mean
Book_Author
Agatha Christie              10  2.855744
Ann M. Martin                10  0.996904
Barbara Cartland             10  4.241176
Carolyn Keene                10  2.465116
Charles Dickens              10  2.735065
Francine Pascal              10  1.169464
Isaac Asimov                 10  3.183565
Nora Roberts                 10  2.656009
Stephen King                 10  3.600363
William Shakespeare          10  3.956572